name: Deploy to EC2 on push main branch

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy NestJS app to EC2 instance
    runs-on: ubuntu-latest
    environment: ec2-server

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Copy source and deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /var/www/nest-app || exit 1
            export DATABASE_URL=${{ secrets.DATABASE_URL }}
            export PORT=${{ vars.PORT }}
            git pull origin main
            yarn install --frozen-lockfile --production
            yarn prisma generate
            yarn prisma migrate deploy
            yarn build
            pm2 restart main || pm2 start dist/main.js --name main --env production
